server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(html|css|js)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.pdf$ {
        types { application/pdf pdf; }
        add_header Cache-Control "public, max-age=86400";
    }
}
